Update Dockerfile.my

diff --git a/Dockerfile.my b/Dockerfile.my
--- a/Dockerfile.my
+++ b/Dockerfile.my
@@ -55,20 +55,33 @@ ENV GOPROXY=http://192.168.0.49:8085/repository/proxy.golang.org/
 # אם יש לך mirror ל-debian ב-Nexus, שים כאן:
 RUN sed -i 's|deb.debian.org|192.168.0.49:8085/repository/debian/|g' /etc/apt/sources.list
 
+# התקן Node דרך nvm
 RUN . "$NVM_DIR/nvm.sh" && \
-  nvm install $NODE_VERSION && \
-  nvm use $NODE_VERSION && \
-  echo "Using bundle identifier: $EXPO_PUBLIC_BUNDLE_IDENTIFIER" && \
-  echo "EXPO_PUBLIC_ENV=$EXPO_PUBLIC_ENV" >> .env && \
-  echo "EXPO_PUBLIC_RELEASE_VERSION=$EXPO_PUBLIC_RELEASE_VERSION" >> .env && \
-  echo "EXPO_PUBLIC_BUNDLE_IDENTIFIER=$EXPO_PUBLIC_BUNDLE_IDENTIFIER" >> .env && \
-  echo "EXPO_PUBLIC_BUNDLE_DATE=$(date -u +"%y%m%d%H")" >> .env && \
-  npm install -g corepack --force && \
-  npm install --global yarn --force && \
-  yarn set version stable && \
-  yarn && \
-  yarn intl:build 2>&1 | tee i18n.log && \
-  if grep -q "invalid syntax" "i18n.log"; then echo "\n\nFound compilation errors!\n\n" && exit 1; else echo "\n\nNo compile errors!\n\n"; fi
+    nvm install $NODE_VERSION && \
+    nvm use $NODE_VERSION && \
+    echo "Using bundle identifier: $EXPO_PUBLIC_BUNDLE_IDENTIFIER" && \
+    echo "EXPO_PUBLIC_ENV=$EXPO_PUBLIC_ENV" >> .env && \
+    echo "EXPO_PUBLIC_RELEASE_VERSION=$EXPO_PUBLIC_RELEASE_VERSION" >> .env && \
+    echo "EXPO_PUBLIC_BUNDLE_IDENTIFIER=$EXPO_PUBLIC_BUNDLE_IDENTIFIER" >> .env && \
+    echo "EXPO_PUBLIC_BUNDLE_DATE=$(date -u +"%y%m%d%H")" >> .env
+
+# הפעל Corepack
+RUN corepack enable
+
+# התקן Yarn הגרסה העולמית
+RUN npm install --global yarn@4.9.4 --force
+
+# ודא ש-Yarn מוגדר לגרסה יציבה
+RUN yarn set version stable
+
+# בניית הפרויקט
+RUN yarn && \
+    yarn intl:build 2>&1 | tee i18n.log && \
+    if grep -q "invalid syntax" "i18n.log"; then \
+        echo "\n\nFound compilation errors!\n\n" && exit 1; \
+    else \
+        echo "\n\nNo compile errors!\n\n"; \
+    fi
 
 # DEBUG
 RUN find ./bskyweb/static && find ./web-build/static
