Update Dockerfiles and .gitignore for build improvements
Changed timezone in Dockerfile to UTC for consistency. Refactored Dockerfile.my build steps to improve environment variable handling, add Sentry DSN, streamline package installation, and include Sentry release build. Added install.sh to .gitignore to prevent tracking of installation script.

diff --git a/Dockerfile.my b/Dockerfile.my
--- a/Dockerfile.my
+++ b/Dockerfile.my
@@ -53,26 +53,23 @@ ENV GOPROXY=http://192.168.0.49:8085/repository/proxy.golang.org/
 
 RUN sed -i 's|deb.debian.org|192.168.0.49:8085/repository/debian/|g' /etc/apt/sources.list
 
-RUN . "$NVM_DIR/nvm.sh" && \
-    nvm install $NODE_VERSION && \
-    nvm use $NODE_VERSION && \
-    echo "Using bundle identifier: $EXPO_PUBLIC_BUNDLE_IDENTIFIER" && \
-    echo "EXPO_PUBLIC_ENV=$EXPO_PUBLIC_ENV" >> .env && \
-    echo "EXPO_PUBLIC_RELEASE_VERSION=$EXPO_PUBLIC_RELEASE_VERSION" >> .env && \
-    echo "EXPO_PUBLIC_BUNDLE_IDENTIFIER=$EXPO_PUBLIC_BUNDLE_IDENTIFIER" >> .env && \
-    echo "EXPO_PUBLIC_BUNDLE_DATE=$(date -u +"%y%m%d%H")" >> .env && \
-    npm install -g corepack --force && \
-    corepack enable && \
-    npm install --global yarn@4.9.4 --force && \
-    yarn set version stable
-
-RUN yarn && \
-    yarn intl:build 2>&1 | tee i18n.log && \
-    if grep -q "invalid syntax" "i18n.log"; then \
-        echo "\n\nFound compilation errors!\n\n" && exit 1; \
-    else \
-        echo "\n\nNo compile errors!\n\n"; \
-    fi
+RUN \. "$NVM_DIR/nvm.sh" && \
+  nvm install $NODE_VERSION && \
+  nvm use $NODE_VERSION && \
+  echo "Using bundle identifier: $EXPO_PUBLIC_BUNDLE_IDENTIFIER" && \
+  echo "EXPO_PUBLIC_ENV=$EXPO_PUBLIC_ENV" >> .env && \
+  echo "EXPO_PUBLIC_RELEASE_VERSION=$EXPO_PUBLIC_RELEASE_VERSION" >> .env && \
+  echo "EXPO_PUBLIC_BUNDLE_IDENTIFIER=$EXPO_PUBLIC_BUNDLE_IDENTIFIER" >> .env && \
+  echo "EXPO_PUBLIC_BUNDLE_DATE=$(date -u +"%y%m%d%H")" >> .env && \
+  echo "EXPO_PUBLIC_SENTRY_DSN=$EXPO_PUBLIC_SENTRY_DSN" >> .env && \
+  npm install -g corepack && \
+  yarn set version stable && \
+  yarn install && \
+  npm install --global yarn && \
+  yarn && \
+  yarn intl:build 2>&1 | tee i18n.log && \
+  if grep -q "invalid syntax" "i18n.log"; then echo "\n\nFound compilation errors!\n\n" && exit 1; else echo "\n\nNo compile errors!\n\n"; fi && \
+  SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN SENTRY_RELEASE=$EXPO_PUBLIC_RELEASE_VERSION SENTRY_DIST=$EXPO_PUBLIC_BUNDLE_IDENTIFIER yarn build-web
 
 # DEBUG
 RUN find ./bskyweb/static && find ./web-build/static
